name = "Memoization"
uuid = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
authors = ["Marius Millea <mariusmillea@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"
MacroTools = "â‰¥0.4.3"
